### ISSUE TITLE
Show selected image count in the FileView

### ISSUE THREAD

**Issue by deepakkumardk** [WindSekirun/NaraeImagePicker#12]
Is there any way to show the selected image count in the toolbar for FileView?

**Comment by WindSekirun** [comment]
No, but i can implement your issue.

In present, FileView only show '$pickerTitle'. Is ok for displaying '$pickerTitle ($pictureCount) in title of Toolbar?

**Comment by deepakkumardk** [comment]
Ya, that's work great.
Thanks, for replying.

**Comment by deepakkumardk** [comment]
And please also update the targetSdkVersion, kotlinVersion, gradle and Glide to latest.

**Comment by WindSekirun** [comment]
There are currently several problems overlapping, so I want to fix other problems as well. The planning schedule is 15 May 2019 15:00 (UTC). If any issue is came out, leave out as **new issue**

**Comment by WindSekirun** [comment]
One more thing, are you using AndroidX? @deepakkumardk

**Comment by deepakkumardk** [comment]
No, currently not.

**Comment by deepakkumardk** [comment]
Hi @WindSekirun 
I have made a PR, please have a look at that.

**Comment by deepakkumardk** [comment]
Hi @WindSekirun 
item.uiSetting.pickerTitle is not working even after calling sendEvent() in library??
Have any idea?

**Comment by WindSekirun** [comment]
@deepakkumardk after apply PR that you made? I'll check.

**Comment by WindSekirun** [comment]
Solved in 2.0.0. Thanks!
