### ISSUE TITLE
Remove kotlin-android-extensions

### ISSUE THREAD

**Issue by WindSekirun** [WindSekirun/NaraeImagePicker#21]
Remove all 'kotlin android extensions' code to avoid memory issues that can occur while caching views.

**Comment by deepakkumardk** [comment]
Hi @WindSekirun 
So after removing the kotlin-android-extension are we migrating this to DataBinding? which is good. But I don't understand what can be the memory issues for caching view as kotlin-android-extension remove all the cache view onDestroy() method. Is there any article/source from which I can go through to dig a little deeper on this topic that it can cause some serious issue.

**Comment by WindSekirun** [comment]
Hi, @deepakkumardk 

Starting from [this commit message](https://android-review.googlesource.com/c/platform/frameworks/support/+/882241), Kotlin-Android-Extensions is not officially recommended (which is not the same as recommendation against) cause these reasons.

1. Cache view into HashMap
2. Doesn't expose nullabilty when views are only present in some configuration.
3. Risk of making RecyclerView not cache ViewHolder.
4. If some views have same `id`, Type inference does not work properly.

Although this problem may not be significant, **the risk exists and is intended to be removed**.

I consider DataBinding as another alternative, but I try to avoid adding dependencies that may not be used by other applications. (The issue in #22 has the same problem.)
 `findViewByIds` with `lateinit` commands also fine to me. (The code will grow a lot, but it doesn't cause any problems)

You can find source of topic in [here](https://www.reddit.com/r/androiddev/comments/ala9p2/why_kotlinx_synthetic_is_no_longer_a_recommended/) and [here](https://proandroiddev.com/the-argument-over-kotlin-synthetics-735305dd4ed0). 

Any other comments are welcome at any time. I don't have enough time to implement right away.

**Comment by deepakkumardk** [comment]
@WindSekirun Thanks for the info, I will work on that.

**Comment by WindSekirun** [comment]
#24 merged.

**Comment by deepakkumardk** [comment]
@WindSekirun now we can close this.
